class MessageType:
    Login = 'login'
    Register = 'register'
    AddFriend = 'add-friend'
    Message = 'message'
    File = 'file'
    JoinRoom = 'join-room'
    MakeRoom = 'make-room'
    RandomRoom = 'random-room'
    GetRoom = 'random-room'
    Attack = 'attack'
    Exit = 'exit'
